const messages = {
  header: {
    title: 'GitYear Studio',
    github: 'GitHub',
    switchLabel: 'Language',
    switchToZh: 'Switch to 中文',
    switchToEn: 'Switch to English',
  },
  home: {
    hero: {
      badge: 'GitHub yearly card · Generate now',
      title: "Enter a GitHub username to aggregate this year's commits, PRs, issues and stars.",
      description:
        'GitYear Studio calls GitHub APIs directly to build a visual share card that works on light and dark backgrounds with one-click PNG export. Optionally provide a token to avoid public rate limits.',
      pillRealtime: 'Live API fetch',
      pillMotion: 'Interactive motion',
      pillColors: 'Chinese / English UI',
    },
    form: {
      title: 'Data form',
      usernameLabel: 'GitHub username',
      usernamePlaceholder: 'e.g. gaearon',
      yearLabel: 'Year',
      tokenLabel: 'GitHub Token (optional)',
      tokenPlaceholder:
        'Prefer a fine-grained token with public_repo only to avoid rate limits.',
      submit: 'Generate card',
      loading: 'Fetching data...',
      sample: 'Use sample',
    },
    errors: {
      fetchFailed: 'Failed to fetch data, please try again later.',
      downloadFailed: 'Export failed, please allow browser screenshot permissions.',
    },
    statsCards: {
      commits: 'Commits',
      prs: 'Merged PRs',
      issues: 'Issues & Discussions',
      stars: 'Starred this year',
    },
    overview: {
      title: 'Contribution makeup & rhythm',
      dateRange: 'Date range: {year}-01-01 ~ {year}-12-31',
      breakdown: 'Contribution breakdown',
      total: '[{total}]',
      timeline: 'Yearly cadence line',
      frequency: '[FREQ]',
      activityIndex: 'Activity index',
      peak: 'Highest peak',
      prCompletion: 'PR completion',
    },
    languages: {
      title: 'Language preference',
      hint: '// Active repos language distribution',
      empty: '[NULL] No public repo language data yet.',
      reposThisYear: 'Active repos this year: <value>{count}</value>',
      reposNote: '// Updated in {year}, reflects active development areas',
    },
    shareCard: {
      title: 'Share card preview',
      description: 'Perfect for Moments / X / Jike. Export HD PNG via the top-right button.',
      export: 'Export PNG',
      contributions: '{count} contributions this year',
      bioFallback: 'This developer is leaving footprints on GitHub with code.',
      shareStats: {
        commits: 'Commits',
        prs: 'Pull Requests',
        issues: 'Issues',
        stars: 'Starred',
      },
    },
    fastShare: {
      title: 'Quick share',
      description:
        'Copy a one-liner or export the card. Unauthenticated GitHub API calls are rate-limited; using your token is recommended.',
      label: 'Share copy',
      placeholder: 'After generating data, a ready-to-copy summary will appear here.',
      copyCta: 'Copy text',
      viewGithub: 'View on GitHub',
    },
    steps: {
      oneTitle: 'Enter GitHub username and pick a year',
      oneDesc: 'Defaults to the current year; add your token to avoid rate limits.',
      twoTitle: 'Instant GitHub API fetch',
      twoDesc: 'Aggregates commits, PRs, issues, stars, active repos and language mix.',
      threeTitle: 'Generate share card & charts',
      threeDesc: 'Visual bars + rhythm line + language radar; copy or export PNG in one click.',
    },
    shareText:
      'In {year}, I made {commits} commits, {prs} PRs, {issues} issues, and starred {stars} projects. Generated by GitYear Studio.',
  },
}

export type AppMessages = typeof messages
export default messages
